In [1]:
import numpy as np
# Numpy Array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
# 1_Dimensional_Array

arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# 2_Dimensional_Array

arr=np.array([[1,2,3,4,5],[201,202,203,204,205]])
arr

array([[  1,   2,   3,   4,   5],
       [201, 202, 203, 204, 205]])

In [5]:
# 3_Dimensional_Array

arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [10]:
# Higher_Dimensional_Array

arr=np.array([1,2,3],ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3]]]]]
number of dimensions : 5


In [16]:
# Methods in numpy
arr=np.array([4,5,7,2,6,1,9,6,10,7])
print(arr)
print(arr.dtype)
print(arr.max())
print(arr.min())
print(arr.mean())
# Press tab after "arr." to see all methods

print(np.sort(arr))
x = np.where(arr == 6)
print(x)

[ 4  5  7  2  6  1  9  6 10  7]
int32
10
1
5.7
[ 1  2  4  5  6  6  7  7  9 10]
(array([4, 7], dtype=int64),)


In [26]:
# Array Slicing
# arr[start:end]
# arr[start:end:step]

# 1_Dimensional_Array
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[:4]) # Print elements of index 0 to 3
print(arr[::2]) # 1 3 5 7 9
print(arr[2::2]) # 3 5 7 9
print(arr[-3:-1]) # Negative indexing 7 8

# 2_Dimensional_Array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2[1,1:4]) # 7 8 9
print(arr2[0:2,2]) # Print 3rd element from both array 3 8
print(arr2[0:2,1:4]) # Print 2nd to 4th element from both array [2 3 4] [7 8 9]


[1 2 3 4]
[1 3 5 7 9]
[3 5 7 9]
[7 8]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [31]:
# Genarating Dummy variable

print(np.zeros(3)) # [0. 0. 0.]
print(np.ones((4,3))) # [[1. 1. 1.] [1. 1. 1.] [1. 1. 1.] [1. 1. 1.]]


[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
# Arrange Array

print(np.arange(0,10,1))
print(np.arange(2,20,.5))
arr=np.arange(-10,11)
print(arr)
print(np.absolute(arr))


[0 1 2 3 4 5 6 7 8 9]
[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5
 16.  16.5 17.  17.5 18.  18.5 19.  19.5]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]
[10  9  8  7  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8  9 10]


In [43]:
# Rendom Value
print(np.random.randn(10)) # 10 Random value
print(np.random.randn(4,3)) # Random Value - Row=4,Column=3
print(np.random.randn(4,3,2)) # Random Value - Problem

print(np.random.randint(11,30)) # 1 Random Value - Between 11 to 30
print(np.random.randint(11,30,3)) # 3 Random Value - Between 11 to 30

[-0.53039654 -1.14007728  0.19623612 -1.48036781  0.67280715  0.33010137
  0.20532862 -0.08813177 -1.83567829  2.92546116]
[[-1.53388794 -2.0146169  -1.11964165]
 [-0.76554857 -1.04113986 -1.64119963]
 [ 0.78740844  0.40804314  0.72211043]
 [-0.17081421 -0.45220322 -0.24440876]]
[[[-0.06351727 -0.18763274]
  [-0.02787321 -0.99943015]
  [-2.60929634  0.12527518]]

 [[-1.81763487  0.13830065]
  [-0.82397333 -1.29090821]
  [ 0.82494034 -0.74825802]]

 [[ 0.14009887 -0.58524212]
  [ 1.4190315   0.61580062]
  [-1.45439583  0.15825472]]

 [[ 0.45070925 -0.90478544]
  [-0.9533497  -1.05097766]
  [ 0.99175537 -1.07093376]]]
29
[20 12 23]


In [ ]:
# Numpy Operation
